feat: 增加点击头像查看原图功能
TRPGEngine/Client pull request #180
Opened 2021-06-02 21:20 UTC by glkwhr

## Summary
* 在`Avatar`中增加点击头像查看大图的功能，由`props`中新增的`clickableForImg`控制。
  * 启用时：
    * 鼠标悬浮在头像上时光标变为放大镜；
    * 点击后打开新的页面查看头像原图（可考虑改为用Modal显示）。
* 对`UserProfile`中的`Avator`启用该功能。

## Test Plan
![Screenshot from 2021-06-02 14-16-09](https://user-images.githubusercontent.com/4232536/120553387-489ded00-c3ad-11eb-98b4-e9650bfd3d96.png)
![Screenshot from 2021-06-02 14-17-20](https://user-images.githubusercontent.com/4232536/120553396-4b004700-c3ad-11eb-9733-b48ad853fc80.png)

2021-06-03 00:59 UTC, moonrailgun commented
可以看一下 `src/web/components/ImageViewer.tsx` 的实现

2021-06-03 04:42 UTC, glkwhr commented
更新：点击头像后使用LightBox在当前页面展示图片

2021-06-03 05:54 UTC, moonrailgun commented
> 更新：点击头像后使用LightBox在当前页面展示图片

一个问题。不是有封装好的组件，并且已经有现成的示例了么？为什么不去使用现成的方法而要自己再做一遍呢？

2021-06-03 05:57 UTC, moonrailgun commented
另外，基于react 组装的思想，不要在一个基础组件中封装与他无关的能力。

一个功能完全的组件并不是一件好事。组件化的设计更加倾向于在业务方通过数个单一功能的组件进行组合

2021-06-04 03:47 UTC, glkwhr commented
更新：改用`ImageVierwer`实现。适用于自定义头像和默认头像。

2021-06-04 03:59 UTC, moonrailgun requested changes

2021-06-04 03:59 UTC, moonrailgun commented on src/web/components/modals/UserProfile.tsx
> +import config from '../../../shared/project.config';
也许可以使用更加短的写法?

```
import config from '@shared/project.config';
```

这是typescript的path功能。好处是如果移动文件路径的话可以保持代码不变

2021-06-04 03:59 UTC, moonrailgun commented on src/web/components/modals/UserProfile.tsx
> +  };
我们为什么要让用户允许在新窗口打开一个默认的字符头像？

我不是很理解。

也许可以试试有avatar就插入ImageVIewer
没有就不插入

```
typeof userInfo.avatar !== undefined ? <ImageViewer>
  <InfoAvatar />
</ImageViewer>: <InfoAvatar />
```

2021-06-04 04:06 UTC, glkwhr commented on src/web/components/modals/UserProfile.tsx
> +  };
我倒没有特别的偏好，只是想着既然能显示就显示了（印象里用过的app里面有可以打开默认头像的）。不过我不是很了解这种特性一般设计上是有什么原则的吗？

2021-06-04 04:23 UTC, moonrailgun commented on src/web/components/modals/UserProfile.tsx
> +  };
因为默认头像打开没有什么意义。你印象中可以打开头像的app，是因为他们的头像是账号生成时就生成的一张图片存起来的，跟用户本身上传区分不开。比如github account的像素头像

还有一个问题就是低版本的edge 对svg text的支持不是很好。所以我从以前的后端返回svg改成了前端动态生成dom来渲染默认头像

2021-06-04 04:38 UTC, glkwhr commented on src/web/components/modals/UserProfile.tsx
> +  };
原来如此，学到了！

2021-06-04 04:55 UTC, glkwhr commented
更新：只在头像URL为非空字符串的情况下启用功能。

2021-06-04 05:43 UTC, moonrailgun approved these changes

2021-06-04 05:44 UTC, moonrailgun commented
LGTM!

2021-06-04 05:44 UTC, merged